version: "3.7"

services:
  frontend:
    container_name: eaf_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./frontend/.env
  backend:
    container_name: eaf_backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 8080:8080
    dns:
      - 8.8.8.8
    volumes:
      - ./backend:/app
    env_file:
      - ./.env
  database:
    container_name: eaf_database
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: eaf_database_user
      MONGO_INITDB_ROOT_PASSWORD: eaf_database_password
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
  # database:
  #   container_name: eaf_database
  #   image: mongodb/mongodb-atlas-local
  #   environment:
  #     - MONGODB_INITDB_ROOT_USERNAME=user
  #     - MONGODB_INITDB_ROOT_PASSWORD=pass
  #   ports:
  #     - 27018:27017
  #   volumes:
  #     - data:/data/db
volumes:
  data:
